title = 'Resume'
locale ="fr-FR"
defaultContentLanguage = "fr"

[languages]
  [languages.fr]
    locale ="fr"
    label ="Français"
    weight = 1
    title = "CV"
  [languages.en]
    locale ="en"
    label ="English"
    weight = 2
    title = "Resume"
